/* Do not edit this file: it was automatically generated */

#ifndef SILVET_DATA_TEMPLATES_H
#define SILVET_DATA_TEMPLATES_H

/* note: intended to parse as both C and C++ */

#define SILVET_TEMPLATE_NOTE_COUNT 88
#define SILVET_TEMPLATE_HEIGHT     545

typedef struct {
    const char *name;
    int lowest;
    int highest;
    float data[SILVET_TEMPLATE_NOTE_COUNT][SILVET_TEMPLATE_HEIGHT];
} silvet_template_t;

static silvet_template_t silvet_templates[13] = {
#include "bassoon.h"
#include "cello.h"
#include "clarinet.h"
#include "flute.h"
#include "guitar.h"
#include "horn.h"
#include "oboe.h"
#include "tenorsax.h"
#include "violin.h"
#include "piano-maps-SptkBGCl.h"
#include "piano1.h"
#include "piano2.h"
#include "piano3.h"
};

#endif
