
ARCHFLAGS	?= -mmacosx-version-min=10.7 -arch x86_64 -arch i386

CXXFLAGS 	+= $(ARCHFLAGS) -DMALLOC_IS_ALIGNED -O3 -ftree-vectorize -I../vamp-plugin-sdk -std=c++11 -stdlib=libc++

LDFLAGS	    	+= $(ARCHFLAGS) -dynamiclib ../vamp-plugin-sdk/libvamp-sdk.a -exported_symbols_list vamp-plugin.list -install_name silvet.dylib

PLUGIN_EXT   := .dylib

MAKEFILE_EXT := .osx

include Makefile.inc

.PHONY: constant-q-cpp
constant-q-cpp: 
	$(MAKE) -C $@ -f Makefile$(MAKEFILE_EXT) libcq.a

