
CFLAGS := -Wall -O3 -fopenmp -ffast-math -msse -msse2 -mfpmath=sse -ftree-vectorize -fPIC -I../vamp-plugin-sdk/ -DUSE_PTHREADS

#CFLAGS := -g -fPIC -I../vamp-plugin-sdk

CXXFLAGS := $(CFLAGS)

VAMPSDK_DIR := ../vamp-plugin-sdk
PLUGIN_LDFLAGS := -lgomp -shared -Wl,-Bsymbolic -Wl,-z,defs -Wl,--version-script=vamp-plugin.map -lpthread

PLUGIN_EXT := .so

include Makefile.inc

constant-q-cpp/libcq.a:
	$(MAKE) -C constant-q-cpp -f Makefile.linux libcq.a
