
TOOLPREFIX     ?= i586-mingw32msvc-
CXX		= $(TOOLPREFIX)g++
CC		= $(TOOLPREFIX)gcc
LD		= $(TOOLPREFIX)g++
AR		= $(TOOLPREFIX)ar
RANLIB		= $(TOOLPREFIX)ranlib

CXXFLAGS 	:= $(CXXFLAGS) -DNDEBUG -O3 -fopenmp -msse -msse2 -ffast-math -mfpmath=sse -Wall -Wextra 
PLUGIN_LDFLAGS 	:= $(LDFLAGS) -shared -static -fopenmp -Wl,--retain-symbols-file=vamp-plugin.list

VAMPSDK_DIR 	:= ../vamp-plugin-sdk
PLUGIN_EXT 	:= .dll

MAKEFILE_EXT    := .mingw32

include Makefile.inc

